### ISSUE TITLE
Alarm bij CDK deploy vanaf lokaal

### ISSUE THREAD

**Issue by marnixdessing** [GemeenteNijmegen/aws-monitoring#153]
We willen een melding als er een CDK deploy vanaf lokaal wordt gedaan. 

Potentiele oplossing: CloudTrail monitoring in de cloudtrail monitoring lambda. We kunnen hier checken of de CDK role assumed wordt in een account door een SSO user / IAM user of iets dat niet CodeBuild is.
```[tasklist]
### Tasks
- [x] Cloudtrail voorbeelden verzamelen (mpa cloudwatch loggroup cloudtraillogs 1. local deploy 2. codecommit)
- [x] Aws-monitoring testen bouwen
- [x] Aws-monitoring filter aanpassen op basis van testbestanden
- [x] Tetsen op sandbox (kan niet)
```

**Comment by WietekeNijmegen** [comment]
```
fields @timestamp, @message, @logStream, @log
| sort @timestamp desc
| filter responseElements.assumedRoleUser.assumedRoleId like /aws-cdk/
| filter userIdentity.sessionContext.sessionIssuer.userName like /AWSReservedSSO/
| filter responseElements.assumedRoleUser.arn like /deploy/
| limit 1000
```

**Comment by WietekeNijmegen** [comment]
Wellicht betere versie:

```
fields @timestamp, @message, @logStream, @log
| sort @timestamp desc
| filter userIdentity.arn like /AWSReservedSSO/
| filter responseElements.assumedRoleUser.arn like /deploy-role/
| limit 1000
```

**Comment by WietekeNijmegen** [comment]
Andere optie leek "assumedRoleUser":{"assumedRoleId"} te zijn, aangezien hier aws-cdk in staat. Maar dit gebeurt ook door het systeem, dan is het we aws-cdk-root. Eventueel waard om een combi van assumroleid aws-cdk (niet root) en deploy-role te doen.

Of niet meer kijken naar AWSReserverdSSO als userIdentity.arn, maar alles dat AWS intern kan zijn uitfilteren en de rest wel laten zien.
